[package]
name = "sunny-vm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zapalloc = "0.0.4"
fnv = "1.0.3"
itertools = "0.9"
